sonar.projectKey=eforms-parser
sonar.projectName=eforms-parser

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=src/eforms/cli.py,src/eforms/stream.py
